# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "alicorn"
  s.version = "0.4.2.pre2"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Somers"]
  s.date = "2013-06-18"
  s.description = "Highly configurable dumb auto-scaler for managing unicorn web servers"
  s.email = "somers.ben@gmail.com"
  s.executables = ["alicorn", "alicorn-profiler"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".travis.yml",
    "CHANGELOG.txt",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "alicorn.gemspec",
    "bin/alicorn",
    "bin/alicorn-profiler",
    "example/config.yml",
    "lib/alicorn.rb",
    "lib/alicorn/dataset.rb",
    "lib/alicorn/errors.rb",
    "lib/alicorn/log_parser.rb",
    "lib/alicorn/profiler.rb",
    "lib/alicorn/scaler.rb",
    "lib/alicorn/version.rb",
    "test/fixtures/sample.alicorn.log",
    "test/helper.rb",
    "test/test_log_parser.rb",
    "test/test_profiler.rb",
    "test/test_scaler.rb"
  ]
  s.homepage = "http://github.com/bensomers/alicorn"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Standalone auto-scaler for unicorn"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<raindrops>, [">= 0.5.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<raindrops>, [">= 0.5.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<raindrops>, [">= 0.5.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

